snowflake-covid:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: gx63281.us-central1.gcp

      user: AIRBYTE_USER                
      password: AIRBYTE_PASSWORD

      role: AIRBYTE_ROLE
      database: AIRBYTE_DATABASE
      warehouse: AIRBYTE_WAREHOUSE
      schema: AIRBYTE_SCHEMA
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt-q

      connect_retries: 0
      connect_timeout: 10
      retry_on_database_errors: False
      retry_all: False